/**
 * <h1>Calculadora</h1>
 * A calculadora realiza operações matemáticas entre números inteiros
 * <p>
 * <b>Note:</b> Leia atentamente a documentação desta classe 
 * para desfrutar dos recursos oferecidos pelo autor
 * 
 * @author Augusto
 * @version 1.0
 * @since 06/07/2022
 */

public class Aula13Calculadora {

	/**
	 * Este método é utilizado para somar dois números inteiros
	 * @param numeroUm este é o primeiro parâmetro do método
	 * @param numeroDois este é o segundo parâmetro do método
	 * @return int o resultado deste método é a soma de dois números
	 */
		public int somar (int numeroUm, int numeroDois) {
			return numeroUm + numeroDois;
		}
}
